### ISSUE TITLE
Tool showing different numbers for same username

### ISSUE THREAD

**Issue by dennisameling** [ishandeveloper/github-wrapped#10]
Thanks for creating this tool @ishandeveloper! Very nice initiative 🚀 

I tried like an hour ago and the stats looked like this:

![image](https://user-images.githubusercontent.com/17739158/103301239-3afcc980-4a01-11eb-8f98-0c4311d62466.png)

An hour later, it now looks like this:

![image](https://user-images.githubusercontent.com/17739158/103301246-418b4100-4a01-11eb-8e10-d49f680617ef.png)

Do you have any clue what might be going on here? 😅 Thanks!

**Comment by ishandeveloper** [comment]
Hi @dennisameling ! Thank you for taking out the time to create this issue.

Actually, those differences in numbers are there because of a change in filtering of results, I made a PR #8 but had to temporarily revert that because of github api's rate limit issue. I've resolved the issues with rate limits and it should work now.

Can you try generating a report again, and let me know whether the stats were correct this time or not? : )

**Comment by dennisameling** [comment]
Thanks for the quick response! 🚀 

Looks like it's back at the original values now. So if I understand correctly, these numbers count for **the past year** (so e.g. Dec 30 2019 - Dec 30 2020) instead of Jan 1st 2020 - Dec 31st 2020?

![image](https://user-images.githubusercontent.com/17739158/103353061-1871bb80-4aa8-11eb-9cb7-c43eb07df1f4.png)

I'm not sure if this info is available in a different place as well, guess I can only cross-check using GitHub's API, correct? 😊 

![image](https://user-images.githubusercontent.com/17739158/103353542-6d620180-4aa9-11eb-9171-cd91e52edc19.png)

**Comment by hugovk** [comment]
I think commits are for the past year but PRs/issues are for calendar year 2020. We can cross-check PRs/issues, the numbers match up with https://githubwrapped.tech/dennisameling:

* 171 PRs https://github.com/search?q=is%3Apr+author%3Adennisameling+created%3A%3E%3D2020-01-01
* 74 issues https://github.com/search?q=is%3Aissue+author%3Adennisameling+created%3A%3E%3D2020-01-01

**Comment by dennisameling** [comment]
Awesome, thanks!! I'll close this issue then. Thanks once again for this awesome tool, wishing you a Happy New Year 🎉
