### ISSUE TITLE
Shows all time not 2020

### ISSUE THREAD

**Issue by hugovk** [ishandeveloper/github-wrapped#11]
<img src=https://user-images.githubusercontent.com/1324225/103331518-045d9800-4a6f-11eb-8ef8-855bed56620d.jpg width=50%>

https://githubwrapped.tech/hugovk says I made 4.2k PRs in this year, but https://github.com/search?q=is%3Apr+author%3Ahugovk+created%3A%3E%3D2020-01-01&type=Issues says it's 1,087 so far this year and https://github.com/search?q=is%3Apr+author%3Ahugovk&type=Issues says 4,744 in total (edit: including private repos. For public/incognito it shows 941 in 2020 and 4,170 in total). 

Similarly:

60 https://github.com/search?q=is%3Apr+author%3Aishandeveloper+created%3A%3E%3D2020-01-01&type=Issues
66 https://github.com/search?q=is%3Apr+author%3Aishandeveloper&type=Issues 

66 https://githubwrapped.tech/ishandeveloper

**Comment by hugovk** [comment]
Issue count is also wrong.

https://github.com/search?q=is%3Aissue+author%3Ahugovk+created%3A%3E%3D2020-01-01&type= says I made 173 in 2020 and 956 in total.

Edit: 159 and 898 for public repos.

**Comment by ishandeveloper** [comment]
Hey, @hugovk I believe it should be fixed in #16  

In case you catch something that looks out of spot, feel free to either comment here and i'll reopen the issue or create a new one. 
Thanks, Happy Holidays :)

**Comment by hugovk** [comment]
Thanks, PR and issue count looks good now!
