### ISSUE TITLE
API not able to display desired message if username is entered wrong

### ISSUE THREAD

**Issue by satyamkr01** [ishandeveloper/github-wrapped#3]

**Comment by ishandeveloper** [comment]
Hey @satyamkr01 Thank you for taking out the time to create this issue and from what I can infer, this was your first issue towards an open-source project. Thank you for giving this repository the opportunity to help you guide in your first contribution. On behalf of everyone here, I'd like to welcome you to the open-source community!

However, I'm afraid there is already an existing issue that tackles this problem. Therefore, I'll be closing this one.

Feel free to create another issue, in case you discover something or have any suggestions. 
Happy holidays! 🎊✨
