### ISSUE TITLE
Wrapped 2021?

### ISSUE THREAD

**Issue by jagannathsrs** [ishandeveloper/github-wrapped#30]
Is this repo actively maintained? Would love to contribute to wrapped 2021 :D

**Comment by ishandeveloper** [comment]
Hey @jagannathsrs, thank you so much for volunteering! 🙂

I'm reviving this repo for 2021 wrapped. Just updated the landing page to reflect the same.
![image](https://user-images.githubusercontent.com/54989142/144596387-55feb284-5c63-4b4e-9705-aaa092a00adf.png)

I'm working on a couple of UI designs and we're hoping to launch the new #GitHubWrapped site this christmas 🎉 

Once finalized, I'll create a couple of issues on this repository, would love to have you as a contributor. Feel free to pick them up once they're up :)

**Comment by nizos** [comment]
> Hey @jagannathsrs, thank you so much for volunteering! 🙂
> 
> I'm reviving this repo for 2021 wrapped. Just updated the landing page to reflect the same.
> ![image](https://user-images.githubusercontent.com/54989142/144596387-55feb284-5c63-4b4e-9705-aaa092a00adf.png)
> 
> I'm working on a couple of UI designs and we're hoping to launch the new #GitHubWrapped site this christmas 🎉 
> 
> Once finalized, I'll create a couple of issues on this repository, would love to have you as a contributor. Feel free to pick them up once they're up :)

I don't think this warrants an issue so I thought I would just drop the notification here. It looks like your domain needs renewal.
